interface=wlan0
driver=nl80211
ssid=@SETUP_SSID@
hw_mode=g
channel=1
country_code=DK
ieee80211n=1
wmm_enabled=1
auth_algs=1
wpa=2
wpa_passphrase=@SETUP_PASSWORD@
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
